config/routes.rb
Rails.application.routes.draw do
  resources :editions
  resources :coaches
  resources :participants
  root 'welcome#home'

end

app/models/edition.rb
# == Schema Information
#
# Table name: editions
#
#  id            :integer          not null, primary key
#  name          :string           not null
#  date_of_event :datetime         not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Edition < ActiveRecord::Base
  validates :name, :date_of_event, presence: true
  validates :name, uniqueness: { case_sensitive: false }

  has_many :edition_participants
  has_many :participants, through: :edition_participants, dependent: :destroy
  has_many :coach_editions
  has_many :coaches, through: :coach_editions, dependent: :destroy

  def self.current
    where(name: 'Mar-2015').last
  end
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  before_action :set_edition, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name:     ENV['ADMIN_USER'],
                               password: ENV['ADMIN_PASS']

  # GET /editions
  # GET /editions.json
  def index
    @editions = Edition.all
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
  end

  # GET /editions/new
  def new
    @edition = Edition.new
  end

  # GET /editions/1/edit
  def edit
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = Edition.new(edition_params)

    respond_to do |format|
      if @edition.save
        format.html { redirect_to @edition, notice: 'Edition was successfully created.' }
        format.json { render :show, status: :created, location: @edition }
      else
        format.html { render :new }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editions/1
  # PATCH/PUT /editions/1.json
  def update
    respond_to do |format|
      if @edition.update(edition_params)
        format.html { redirect_to @edition, notice: 'Edition was successfully updated.' }
        format.json { render :show, status: :ok, location: @edition }
      else
        format.html { render :edit }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition.destroy
    respond_to do |format|
      format.html { redirect_to editions_url, notice: 'Edition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_edition
    @edition = Edition.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def edition_params
    params.require(:edition).permit(:name, :date_of_event)
  end
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/editions/_form.html.erb
<%= form_for(@edition) do |f| %>
  <% if @edition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@edition.errors.count, "error") %> prohibited this edition from being saved:</h2>

      <ul>
      <% @edition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date_of_event %><br>
    <%= f.datetime_select :date_of_event %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editions/edit.html.erb
<h1>Editing Edition</h1>

<%= render 'form' %>

<%= link_to 'Show', @edition %> |
<%= link_to 'Back', editions_path %>

app/views/editions/index.html.erb
<h1>Listing Editions</h1>

<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of event</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @editions.each do |edition| %>
      <tr>
        <td><%= edition.name %></td>
        <td><%= edition.date_of_event %></td>
        <td><%= link_to 'Show', edition %></td>
        <td><%= link_to 'Edit', edit_edition_path(edition) %></td>
        <td><%= link_to 'Destroy', edition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Edition', new_edition_path %>

app/views/editions/new.html.erb
<h1>New Edition</h1>

<%= render 'form' %>

<%= link_to 'Back', editions_path %>

app/views/editions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @edition.name %>
</p>

<p>
  <strong>Date of event:</strong>
  <%= @edition.date_of_event %>
</p>

<%= link_to 'Edit', edit_edition_path(@edition) %> |
<%= link_to 'Back', editions_path %>