config/routes.rb
Rails.application.routes.draw do
  resources :editions
  resources :coaches
  resources :participants
  root 'welcome#home'

end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id                          :integer          not null, primary key
#  name                        :string           not null
#  email                       :string           not null
#  attended_meetups            :boolean
#  student_or_employed         :string
#  living_in_chennai           :boolean
#  have_ruby_configured_laptop :boolean
#  remarks                     :text
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  profession                  :string
#
# Indexes
#
#  index_participants_on_email  (email)
#

class Participant < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email, email: true
  validate :current_edition_present
  validate :email_within_current_edition, on: :create

  has_many :edition_participants
  has_many :editions, through: :edition_participants

  before_save { edition_participants.build(edition: Edition.current) unless already_registered_for?(Edition.current) }

  def self.student_or_employed_options
    %w(Student Professional)
  end

  def self.attended_meetups_options
    [['have', true], ["haven't", false]]
  end

  def self.have_ruby_configured_laptop_options
    [['have', true], ["don't have", false]]
  end

  def self.living_in_chennai_options
    [['live', true], ["don't live", false]]
  end

  private

  def already_registered_for?(edition)
    editions.include?(edition)
  end

  def current_edition_present
    errors.add(:base, 'Current edition not configured/found') unless Edition.current.present?
  end

  def email_within_current_edition
    errors.add(:email, 'is already registered for this edition') if already_registered_for?(Edition.current)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name:     ENV['ADMIN_USER'],
                               password: ENV['ADMIN_PASS'],
                               except:   :create

  # GET /participants
  # GET /participants.json
  def index
    # @participants = Participant.all
    @participants = current_edition.nil? ? [] : current_edition.participants.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.where(email: participant_params[:email]).last
    @participant ||= Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json do
          error_str = @participant.errors.full_messages.join(', ')
          error_str = 'Some error occurred' if error_str.empty?
          render text: error_str.html_safe, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def current_edition
    Edition.current
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_participant
    @participant = Participant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def participant_params
    params.require(:participant).permit(:name, :email, :attended_meetups, :living_in_chennai, :student_or_employed, :have_ruby_configured_laptop, :remarks)
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant, format: :json, remote: true, html: {class: 'form-inline', id: 'participant-form'}) do |f| %>

	<div class='form-notice alert-danger'>
	</div>

	My name is <%= f.text_field :name %>

	<br>
	I'm a <%= f.select :student_or_employed,
		options_for_select(Participant.student_or_employed_options) %>.

	<br>
	I <%= f.select :attended_meetups,
		options_for_select(Participant.attended_meetups_options) %>
		attended Chennai.rb meetups before.

	<br>
	I <%= f.select :have_ruby_configured_laptop,
		options_for_select(Participant.have_ruby_configured_laptop_options) %>
		a Ruby configured laptop.

	<br>
	I <%= f.select :living_in_chennai,
		options_for_select(Participant.living_in_chennai_options) %>
		in Chennai.

	<br>
	My email-id is <%= f.email_field :email %>

	<br>
	<%= f.submit 'Lets go', class: 'btn btn-primary' %>

<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Attended meetups</th>
      <th>Living in chennai</th>
      <th>Student or employed</th>
      <th>Have ruby configured laptop</th>
      <th>Remarks</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.email %></td>
        <td><%= tick_mark(participant.attended_meetups) %></td>
        <td><%= tick_mark(participant.living_in_chennai) %></td>
        <td><%= participant.student_or_employed %></td>
        <td><%= tick_mark(participant.have_ruby_configured_laptop) %></td>
        <td><%= participant.remarks %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<div class="page-header">
  <h1>New participant</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Attended meetups:</strong>
  <%= @participant.attended_meetups %>
</p>

<p>
  <strong>Living in chennai:</strong>
  <%= @participant.living_in_chennai %>
</p>

<p>
  <strong>Student or employed:</strong>
  <%= @participant.student_or_employed %>
</p>

<p>
  <strong>Have ruby configured laptop:</strong>
  <%= @participant.have_ruby_configured_laptop %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @participant.remarks %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>