config/routes.rb
Rails.application.routes.draw do
  resources :editions
  resources :coaches
  resources :participants
  root 'welcome#home'

end

app/models/coach.rb
# == Schema Information
#
# Table name: coaches
#
#  id                :integer          not null, primary key
#  name              :string           not null
#  email             :string           not null
#  twitter_handle    :string
#  attended_meetups  :boolean
#  living_in_chennai :boolean
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Coach < ActiveRecord::Base
  validates :name, :email, presence: true

  has_many :coach_editions
  has_many :coaches, through: :coach_editions

  def self.attended_meetups_options
    [['have', true], ["haven't", false]]
  end

  def self.living_in_chennai_options
    [['live', true], ["don't live", false]]
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: ENV['ADMIN_USER'], password: ENV['ADMIN_PASS'], except: :create

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_coach
    @coach = Coach.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def coach_params
    params.require(:coach).permit(:name, :email, :twitter_handle, :attended_meetups, :living_in_chennai)
  end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_for(@coach) do |f| %>
  <% if @coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
      <% @coach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :twitter_handle %><br>
    <%= f.text_field :twitter_handle %>
  </div>
  <div class="field">
    <%= f.label :attended_meetups %><br>
    <%= f.check_box :attended_meetups %>
  </div>
  <div class="field">
    <%= f.label :living_in_chennai %><br>
    <%= f.check_box :living_in_chennai %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing coach</h1>

<%= render 'form' %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<h1>Listing coaches</h1>

<div class="table-responsive">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Twitter handle</th>
      <th>Attended meetups</th>
      <th>Living in chennai</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.name %></td>
        <td><%= coach.email %></td>
        <td><%= coach.twitter_handle %></td>
        <td><%= tick_mark(coach.attended_meetups) %></td>
        <td><%= tick_mark(coach.living_in_chennai) %></td>
        <td><%= link_to 'Show', coach %></td>
        <td><%= link_to 'Edit', edit_coach_path(coach) %></td>
        <td><%= link_to 'Destroy', coach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Coach', new_coach_path %>

app/views/coaches/new.html.erb
<div class="page-header">
  <h1>New participant</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coach.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @coach.email %>
</p>

<p>
  <strong>Twitter handle:</strong>
  <%= @coach.twitter_handle %>
</p>

<p>
  <strong>Attended meetups:</strong>
  <%= @coach.attended_meetups %>
</p>

<p>
  <strong>Living in chennai:</strong>
  <%= @coach.living_in_chennai %>
</p>

<%= link_to 'Edit', edit_coach_path(@coach) %> |
<%= link_to 'Back', coaches_path %>